### ISSUE TITLE
Nicer way to allocate an empty string

### ISSUE THREAD

**Issue by JensRantil** [fimblo/prompt2#11]
Is `char digestedPrompt[1024] = "";` nicer than https://github.com/fimblo/prompt2/blob/8c817cdfecd3a751bb9b0f1c213373e80b2b32e8/src/prompt.c#L74? Maybe it doesn't compile, though... 😊

**Comment by fimblo** [comment]
I'll give it a shot! It's certainly easier on the eyes.

**Comment by fimblo** [comment]
Compiles nicely. Thank you for the feedback.

**Comment by JensRantil** [comment]
I noticed you manually closed this issue. Did you know you can add "Fixes #XXX" in a commit and once it merges into trunk/mainline/main branch, the issue is automagically closed? It's pretty neat. More [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
