### ISSUE TITLE
Scary itoa(...) memory allocation

### ISSUE THREAD

**Issue by JensRantil** [fimblo/prompt2#12]
I find https://github.com/fimblo/prompt2/blob/8c817cdfecd3a751bb9b0f1c213373e80b2b32e8/src/prompt.c#L37-L42 to be a little scary having unintended side-effects. Did you consider alternate ways of implementing it without having to use a singleton `static` buffer?

**Comment by fimblo** [comment]
No, I just wanted something to work at the time, and I haven't come around to getting back to it. Thank you for highlighting this.
