### ISSUE TITLE
Are error checked for in `main(...)`?

### ISSUE THREAD

**Issue by JensRantil** [fimblo/prompt2#14]
I notice that the main function doesn't return anything else than `0`. That makes me suspicious. Should be checking for any kind of errors in the application?

**Comment by fimblo** [comment]
Long story short:
1. yes, there should be more checks for errors, and
2. I intend the eventual prompt program to always default to a plain bash prompt (outputting PS1), so many failures can, instead of doing error handling, just default to that... or that's kind of how I'm thinking about it.
