### ISSUE TITLE
Idea on how to pass configuration into prompt2

### ISSUE THREAD

**Issue by fimblo** [fimblo/prompt2#26]
This thread can be used to comment on the content of the [prompt configuration proposal](https://github.com/fimblo/prompt2/blob/main/prompt-configuration-idea.md)

**Comment by fimblo** [comment]
One problem with the proposed solution pointed out by a colleague of mine was the sheer number of environment variables this will require. Managing these will be a pain. 
He immediately proposed a solution to this - to use a config file - and upon shell startup, read the file once and output valid shell environment variables.
I could call it from a shell function so as to make it possible to export.

I imagine the file could be a yaml file, or like another colleague jokingly suggested - a CSS file (so inheritance can be used).

I kind of like this idea.

**Comment by fimblo** [comment]
Hm. I know I'm expanding scope lots-and-lots, but I _have_ played with the idea of a wysiwig prompt-creator program, maybe in a browser or using ncurses or something. That could output a config file...

**Comment by JensRantil** [comment]
Hello! I had a look at https://github.com/fimblo/prompt2/blob/main/prompt-configuration-idea.md and I also vote for a config file. It feels more common for config.

However, in the spirit of not having to need a YAML parser, I would probably vote for something like
```ini
[CWD]
full=xyz
basename=abc

[Repo]
...
```
(INI file style) or even simpler
```ini
CWD.full=xyz
CWD.basename=abc
Repo.has_upstream=0
...
```

Also, `!0` feels off. Why not...`1`?

**Comment by fimblo** [comment]
mm, did you see the comments I wrote above? That is, that prompt2 reads environment variables, but these are created by another program and spit out upon shell startup. 

!0 is just my way of indicating anything which isn't zero. sometimes, like with `staged` it can have the value 3 (if there are three staged files).

**Comment by fimblo** [comment]
maybe I'm making bigger deal than I need to. reading a small config file for the prompt to read every time I hit enter won't be a big deal after its read the first time.

**Comment by JensRantil** [comment]
> mm, did you see the comments I wrote above? That is, that prompt2 reads environment variables, but these are created by another program and spit out upon shell startup.
> 
> !0 is just my way of indicating anything which isn't zero. sometimes, like with `staged` it can have the value 3 (if there are three staged files).

Hah, I probably did _not_ read those careful enough. 😊

**Comment by JensRantil** [comment]
> maybe I'm making bigger deal than I need to. reading a small config file for the prompt to read every time I hit enter won't be a big deal after its read the first time.

I don't think it should be a big issue, but maybe you could do a super small quick and dirty benchmark to see what latency it would add?

**Comment by fimblo** [comment]
Yeah, good idea. Will do.

**Comment by fimblo** [comment]
I forgot how using C exchanges convenience and sanity for speed.

With 4 lines of config, it took 11ms to run.
With 200 lines of config, it took 12ms to run.

And these are probably just rounding errors or fluctuations in the system load.  (oh and the file wasn't cached)

Ok, I can do whatever I feel like, and don't need to worry about speed :) Thanks Jens for reminding me to check if this actually was a problem I needed to solve!

**Comment by fimblo** [comment]
Decided to go with a config file.
