### ISSUE TITLE
Customise the right-aligned part

### ISSUE THREAD

**Issue by JensRantil** [fimblo/prompt2#44]
I recently learned that the right-aligned part (AWS credentials expiration count-down) is fairly hardcoded. Here is a small feature request to move such logic out into the config file to be able to customise the right-aligned part (GCP credentials countdown? Time of day? Etc.).

**Comment by fimblo** [comment]
Could you clarify:
- are you asking if other widgets can be on the right? If so yes: any
existing widget can be right aligned.
- if you are asking for a feature request to have arbitrary widgets (like
gcp token time) through shell exec, well that would be interesting now.

**Comment by fimblo** [comment]
Added the arbitrary widget idea as a separate issue: GH-46
