### ISSUE TITLE
Use snake case instead?

### ISSUE THREAD

**Issue by JensRantil** [fimblo/prompt2#6]
I just read through https://github.com/fimblo/prompt2/blob/8c817cdfecd3a751bb9b0f1c213373e80b2b32e8/src/get-status.h and noticed that many of the functions are camelCase and I think it's more common to use snake_case in the C programming language. This is a nitpicky issue, though! ☺️

**Comment by fimblo** [comment]
Thanks for pointing this out - I'm actually not used to camelCase - it was only when I programmed in Java that I used it - and at my current workplace, which is a typescript shop.
