### ISSUE TITLE
Use strcmp?

### ISSUE THREAD

**Issue by JensRantil** [fimblo/prompt2#8]
Minor, but I noticed https://github.com/fimblo/prompt2/blob/8c817cdfecd3a751bb9b0f1c213373e80b2b32e8/src/prompt.c#L81. Using `strcmp(...)` might make the code a little more readable.

**Comment by fimblo** [comment]
mm, good idea.

**Comment by fimblo** [comment]
Looked at this now, and I'm wondering what you meant. Isn't strcmp used to compare null-terminated strings? Here I'm looking at individual characters in the string.
